[profile.default]
src = 'contracts'
out = 'out'
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
    '@manifoldxyz/creator-core-solidity=lib/creator-core-solidity',
    '@manifoldxyz/libraries-solidity=lib/libraries-solidity',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config